-- RECIV_Bavaria_Text_Names
-- Author: JNR
--------------------------------------------------------------

-- English
--------------------------------------------------------------
INSERT OR IGNORE INTO LocalizedText
		(Language,	Tag,												Text)
VALUES	('en_US',	'LOC_CITY_NAME_INGOLSTADT',							'Ingolstadt'),
		('en_US',	'LOC_CITY_NAME_BAYREUTH',							'Bayreuth'),
		('en_US',	'LOC_CITY_NAME_PASSAU',								'Passau'),
		('en_US',	'LOC_CITY_NAME_COBURG',								'Coburg'),
		('en_US',	'LOC_CITY_NAME_LANDSHUT',							'Landshut'),
		('en_US',	'LOC_CITY_NAME_ERLANGEN',							'Erlangen'),
		('en_US',	'LOC_CITY_NAME_BAMBERG',							'Bamberg'),
		('en_US',	'LOC_CITY_NAME_SCHWEINFURT',						'Schweinfurt'),
		('en_US',	'LOC_CITY_NAME_FURTH',								'Fürth'),
		('en_US',	'LOC_CITY_NAME_FREISING',							'Freising'),
		('en_US',	'LOC_CITY_NAME_HOF',								'Hof'),
		('en_US',	'LOC_CITY_NAME_AMBERG',								'Amberg'),
		('en_US',	'LOC_CITY_NAME_ANSBACH',							'Ansbach'),
		('en_US',	'LOC_CITY_NAME_ROSENHEIM',							'Rosenheim'),
		('en_US',	'LOC_CITY_NAME_KEMPTEN',							'Kempten'),
		('en_US',	'LOC_CITY_NAME_STRAUBING',							'Straubing'),
		('en_US',	'LOC_CITY_NAME_BAD_KISSINGEN',						'Bad Kissingen'),
		('en_US',	'LOC_CITY_NAME_ASCHAFFENBURG',						'Aschaffenburg'),
		('en_US',	'LOC_CITY_NAME_MEMMINGEN',							'Memmingen'),
		('en_US',	'LOC_CITY_NAME_ERDING',								'Erding'),
		('en_US',	'LOC_CITY_NAME_PARTENKIRCHEN',						'Partenkirchen'),
		('en_US',	'LOC_CITY_NAME_TRAUNSTEIN',							'Traunstein'),
		('en_US',	'LOC_CITY_NAME_NORDLINGEN',							'Nördlingen'),
		('en_US',	'LOC_CITY_NAME_STARNBERG',							'Starnberg'),
		('en_US',	'LOC_CITY_NAME_OBERSTORF',							'Oberstorf'),
		('en_US',	'LOC_CITY_NAME_BAD_TOLZ',							'Bad Tölz'),
--		('en_US',	'LOC_CITY_NAME_MUNICH_CAPITAL',						'Munich'),		
--		('en_US',	'LOC_CITY_NAME_NUREMBERG',							'Nuremberg'),
--		('en_US',	'LOC_CITY_NAME_AUGSBURG',							'Augsburg'),
--		('en_US',	'LOC_CITY_NAME_REGENSBURG',							'Regensburg'),	
--		('en_US',	'LOC_CITY_NAME_WURZBURG',							'Würzburg'),

		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MALE_1',					'Anderl'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MALE_2',					'Gustl'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MALE_3',					'Odilo'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MALE_4',					'Schorsch'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MALE_5',					'Sepp'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MALE_6',					'Stachus'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MALE_7',					'Tassilo'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MALE_8',					'Toni'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MALE_9',					'Veit'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MALE_10',					'Wigerl'),
		
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_1',					'Bärbl'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_2',					'Dodo'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_3',					'Evi'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_4',					'Gretl'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_5',					'Hannerl'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_6',					'Lisl'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_7',					'Maria'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_8',					'Resi'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_9',					'Traudl'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_10',				'Zenzi'),

		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_1',			'Alois'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_2',			'Anton'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_3',			'Ferdinand'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_4',			'Franz'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_5',			'Korbinian'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_6',			'Leopold'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_7',			'Ludwig'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_8',			'Maximilian'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_9',			'Severin'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_10',			'Xaver'),
		
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_1',			'Antonia'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_2',			'Dorothea'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_3',			'Elisabeth'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_4',			'Franziska'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_5',			'Lotti'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_6',			'Steffi'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_7',			'Theresa'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_8',			'Susi'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_9',			'Victoria'),
		('en_US',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_10',			'Vroni'),

		('en_US',	'LOC_NAMED_RIVER_MAIN_NAME',						'Main River'),
		('en_US',	'LOC_NAMED_RIVER_ISAR_NAME',						'Isar River'),
		('en_US',	'LOC_NAMED_RIVER_INN_NAME',							'Inn River'),
		('en_US',	'LOC_NAMED_RIVER_ILLER_NAME',						'Iller River'),
		('en_US',	'LOC_NAMED_RIVER_LECH_NAME',						'Lech River'),
		('en_US',	'LOC_NAMED_RIVER_ALTMUEHL_NAME',					'Altmühl River'),
		('en_US',	'LOC_NAMED_RIVER_WERTACH_NAME',						'Wertach River'),

		('en_US',	'LOC_NAMED_VOLCANO_PARKSTEIN_NAME',					'Parkstein'),
		('en_US',	'LOC_NAMED_VOLCANO_LINDENSTUMPF_NAME',				'Lindenstumpf'),
		('en_US',	'LOC_NAMED_VOLCANO_RAUHER_KULM_NAME',				'Rauher Kulm'),

		('en_US',	'LOC_NAMED_MOUNTAIN_BAVARIAN_FOREST_NAME',			'Bavarian Forest'),
		('en_US',	'LOC_NAMED_MOUNTAIN_UPPER_PALATINE_FOREST_NAME',	'Upper Palatine Forest'),
		('en_US',	'LOC_NAMED_MOUNTAIN_FICHTEL_MOUNTAINS_NAME',		'Fichtel Mountains'),
		('en_US',	'LOC_NAMED_MOUNTAIN_FRANCONIAN_JURA_NAME',			'Franconian Jura'),

		('en_US',	'LOC_NAMED_LAKE_TEGERNSEE_NAME',					'Tegernsee'),
		('en_US',	'LOC_NAMED_LAKE_STAFFELSEE_NAME',					'Staffelsee');
--------------------------------------------------------------

-- German
--------------------------------------------------------------
INSERT OR IGNORE INTO LocalizedText
		(Language,	Tag,												Text)
VALUES	('de_DE',	'LOC_CITY_NAME_MUNICH',								'Munich'),

--		('de_DE',	'LOC_CITY_NAME_NUREMBERG',							'Nuremberg'),
--		('de_DE',	'LOC_CITY_NAME_AUGSBURG',							'Augsburg'),
--		('de_DE',	'LOC_CITY_NAME_REGENSBURG',							'Regensburg'),	
		('de_DE',	'LOC_CITY_NAME_INGOLSTADT',							'Ingolstadt'),
--		('de_DE',	'LOC_CITY_NAME_WURZBURG',							'Würzburg'),
		('de_DE',	'LOC_CITY_NAME_BAYREUTH',							'Bayreuth'),
		('de_DE',	'LOC_CITY_NAME_PASSAU',								'Passau'),
		('de_DE',	'LOC_CITY_NAME_COBURG',								'Coburg'),
		('de_DE',	'LOC_CITY_NAME_LANDSHUT',							'Landshut'),
		('de_DE',	'LOC_CITY_NAME_ERLANGEN',							'Erlangen'),
		('de_DE',	'LOC_CITY_NAME_BAMBERG',							'Bamberg'),
		('de_DE',	'LOC_CITY_NAME_SCHWEINFURT',						'Schweinfurt'),
		('de_DE',	'LOC_CITY_NAME_FURTH',								'Fürth'),
		('de_DE',	'LOC_CITY_NAME_FREISING',							'Freising'),
		('de_DE',	'LOC_CITY_NAME_HOF',								'Hof'),
		('de_DE',	'LOC_CITY_NAME_AMBERG',								'Amberg'),
		('de_DE',	'LOC_CITY_NAME_ANSBACH',							'Ansbach'),
		('de_DE',	'LOC_CITY_NAME_ROSENHEIM',							'Rosenheim'),
		('de_DE',	'LOC_CITY_NAME_KEMPTEN',							'Kempten'),
		('de_DE',	'LOC_CITY_NAME_STRAUBING',							'Straubing'),
		('de_DE',	'LOC_CITY_NAME_BAD_KISSINGEN',						'Bad Kissingen'),
		('de_DE',	'LOC_CITY_NAME_ASCHAFFENBURG',						'Aschaffenburg'),
		('de_DE',	'LOC_CITY_NAME_MEMMINGEN',							'Memmingen'),
		('de_DE',	'LOC_CITY_NAME_ERDING',								'Erding'),
		('de_DE',	'LOC_CITY_NAME_PARTENKIRCHEN',						'Partenkirchen'),
		('de_DE',	'LOC_CITY_NAME_TRAUNSTEIN',							'Traunstein'),
		('de_DE',	'LOC_CITY_NAME_NORDLINGEN',							'Nördlingen'),
		('de_DE',	'LOC_CITY_NAME_STARNBERG',							'Starnberg'),
		('de_DE',	'LOC_CITY_NAME_OBERSTORF',							'Oberstorf'),
		('de_DE',	'LOC_CITY_NAME_BAD_TOLZ',							'Bad Tölz'),

		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MALE_1',					'Anderl'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MALE_2',					'Gustl'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MALE_3',					'Odilo'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MALE_4',					'Schorsch'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MALE_5',					'Sepp'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MALE_6',					'Stachus'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MALE_7',					'Tassilo'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MALE_8',					'Toni'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MALE_9',					'Veit'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MALE_10',					'Wigerl'),
		
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_1',					'Bärbl'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_2',					'Dodo'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_3',					'Evi'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_4',					'Gretl'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_5',					'Hannerl'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_6',					'Lisl'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_7',					'Maria'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_8',					'Resi'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_9',					'Traudl'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_10',				'Zenzi'),

		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_1',			'Alois'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_2',			'Anton'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_3',			'Ferdinand'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_4',			'Franz'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_5',			'Korbinian'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_6',			'Leopold'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_7',			'Ludwig'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_8',			'Maximilian'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_9',			'Severin'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_10',			'Xaver'),
		
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_1',			'Antonia'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_2',			'Dorothea'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_3',			'Elisabeth'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_4',			'Franziska'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_5',			'Lotti'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_6',			'Steffi'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_7',			'Theresa'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_8',			'Susi'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_9',			'Victoria'),
		('de_DE',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_10',			'Vroni');

INSERT OR IGNORE INTO LocalizedText
		(Language,	Tag,												Text,																						Gender,			Plurality)
VALUES	('de_DE',	'LOC_NAMED_RIVER_MAIN_NAME',						'Main|Main|Main|Mains|Main',																'masculine',	1),
		('de_DE',	'LOC_NAMED_RIVER_ISAR_NAME',						'Isar|Isar|Isar|Isar|Isar',																	'feminine',		1),
		('de_DE',	'LOC_NAMED_RIVER_INN_NAME',							'Inn|Inn|Inn|Inns|Inn',																		'masculine',	1),
		('de_DE',	'LOC_NAMED_RIVER_ILLER_NAME',						'Iller|Iller|Iller|Iller|Iller',															'feminine',		1),
		('de_DE',	'LOC_NAMED_RIVER_LECH_NAME',						'Lech|Lech|Lech|Lechs|Lech',																'masculine',	1),
		('de_DE',	'LOC_NAMED_RIVER_ALTMUEHL_NAME',					'Altmühl|Altmühl|Altmühl|Altmühl|Altmühl',													'feminine',		1),
		('de_DE',	'LOC_NAMED_RIVER_WERTACH_NAME',						'Wertach|Wertach|Wertach|Wertach|Wertach',													'feminine',		1),

		('de_DE',	'LOC_NAMED_VOLCANO_PARKSTEIN_NAME',					'Parkstein|Parkstein|Parkstein|Parksteins|Parkstein',										'masculine',	1),
		('de_DE',	'LOC_NAMED_VOLCANO_LINDENSTUMPF_NAME',				'Lindenstumpf|Lindenstumpf|Lindenstumpf|Lindenstumpfs|Lindenstumpf',						'masculine',	1),
		('de_DE',	'LOC_NAMED_VOLCANO_RAUHER_KULM_NAME',				'Rauher Kulm|Rauher Kulm|Rauhen Kulm|Rauhen Kulms|Rauher Kulm',								'masculine',	1),

		('de_DE',	'LOC_NAMED_MOUNTAIN_BAVARIAN_FOREST_NAME',			'Bayerischer Wald|Bayerischer Wald|Bayerischen Wald|Bayerischen Waldes|Bayerischer Wald',	'masculine',	1),
		('de_DE',	'LOC_NAMED_MOUNTAIN_UPPER_PALATINE_FOREST_NAME',	'Oberfpälzer Wald|Oberfpälzer Wald|Oberfpälzer Wald|Oberfpälzer Waldes|Oberfpälzer Wald',	'masculine',	1),
		('de_DE',	'LOC_NAMED_MOUNTAIN_FICHTEL_MOUNTAINS_NAME',		'Fichtelgebirge|Fichtelgebirge|Fichtelgebirge|Fichtelgebirges|Fichtelgebirge',				'neuter',		1),
		('de_DE',	'LOC_NAMED_MOUNTAIN_FRANCONIAN_JURA_NAME',			'Fränkische Alb|Fränkische Alb|Fränkischen Alb|Fränkischen Alb|Fränkische Alb',				'feminine',		1),

		('de_DE',	'LOC_NAMED_LAKE_TEGERNSEE_NAME',					'Tegernsee|Tegernsee|Tegernsee|Tegernsees|Tegernsee',										'masculine',	1),
		('de_DE',	'LOC_NAMED_LAKE_STAFFELSEE_NAME',					'Staffelsee|Staffelsee|Staffelsee|Staffelsees|Staffelsee',									'masculine',	1);
--------------------------------------------------------------