-- RECIV_Bavaria_Text_Nomina
-- Author: JNR
--------------------------------------------------------------

-- All Languages
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText
		(Language,	Tag,									Text)
SELECT	Language,	TRIM(Tag,'GERMANY') || 'JNR_BAVARIA',	Text
FROM	LocalizedText
WHERE	Tag LIKE '%CIVILIZATION_GERMANY';
--------------------------------------------------------------

-- English
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES

	-- Tier 2
	
	-- Monarchy
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  'Count {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  'Countess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  'County of {1_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  'County of {1_Capital}'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  'Prince {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  'Princess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  'Principality of  {2_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  'Principality of {2_Capital}'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Duke {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Duchess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Duchy of {1_Name}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Duchy of {1_Name}'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  'King {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  'Queen {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  'Kingdom of {1_Name}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  'Kingdom of {1_Name}'	),

	-- Theocracy - Military Order
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  'Grand Master {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  'Grand Mistress {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  'Royal {1_Adjective} Order of Saint George'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  'Royal {1_Adjective} Order of Saint George'	),

	-- Theocracy - Christian / Catholic
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  'Prince-Abbot {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  'Princess-Abbess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  'Prince-Abbey of {1_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  'Prince-Abbey of {1_Capital}'	),
	
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  'Prince-Bishop {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  'Princess-Bishopess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  'Prince-Bishopric of {1_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  'Prince-Bishopric of {1_Capital}'	),
	
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Prince-Archbishop {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Princess-Archbishopess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Prince-Archbishopric of {1_Name}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Prince-Archbishopric of {1_Name}'	),
	
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  'Pope {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  'Popess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Capital} Papacy'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Capital} Papacy'	),
	
	-- Theocracy - Protestant
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  'Pastor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  'Pastoress {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  'Congregation of {1_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  'Congregation of {1_Capital}'	),
	
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  'Dean {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  'Dean {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  'Deanery of {1_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  'Deanery of {1_Capital}'	),
	
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Regional Bishop {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Regional Bishopess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Bishopric {1_Name}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Bishopric {1_Name}'	),
	
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  'Country Bishop {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  'Country Bishop {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective} Evangelical Church'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective} Evangelical Church'	),
	
	-- Merchant Republic - Tiny
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  'Mayor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  'Mayor {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  'Free City of {1_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  'Free City of {1_Capital}'	),
	
	-- Merchant Republic - Land
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  'Foremost Losunger {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  'Foremost Losungerin {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  'Free City of {2_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  'Free City of {2_Capital}'	),
	
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  'Lord Mayor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  'Lord Mayor {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  '{1_Capital} Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  '{1_Capital} Republic'	),
	
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  'Chairman {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  'Chairwoman {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  'Bavarian League'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  'Bavarian League'	),
	
	-- Merchant Republic - Sea
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  'Foremost Losunger {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  'Foremost Losungerin {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  'Free City of {2_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  'Free City  of {2_Capital}'	),
	
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  'Lord Mayor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  'Lord Mayor {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  '{2_Capital} Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  '{2_Capital} Republic'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  'Chairman {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  'Chairwoman {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  'Bavarian League'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  'Bavarian League'	),

	-- Tier 3
	
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  'State Commissioner General {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  'State Commissioner General {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective} Ordnungszelle'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective} Ordnungszelle'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  'General Secretary {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  'General Secretary {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  'Bavarian Council Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  'Bavarian Council Republic'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  'Prime Minister {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  'Prime Minister {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  'Freistaat {1_Name}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  'Freistaat {1_Name}'	);
--------------------------------------------------------------

-- German
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES

	-- Tier 2
	
	-- Monarchy
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  'Graf {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  'Gräfin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  'Grafschaft {1_Capital}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  'Grafschaft {1_Capital}'	),

	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  'Fürst {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  'Fürstin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  'Fürstentum {2_Capital}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  'Fürstentum {2_Capital}'	),

	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Herzog {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Herzögin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Herzogtum {1_Name}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Herzogtum {1_Name}'	),

	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  'König {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  'Königin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  'Königreich {1_Name}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  'Königreich {1_Name}'	),

	-- Theocracy - Military Order
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  'Großmeister {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  'Großmeisterin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  'Königlich Bayerischer Hausritterorden vom Heiligen Georg'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  'Königlich Bayerischer Hausritterorden vom Heiligen Georg'	),

	-- Theocracy - Christian / Catholic
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  'Fürstabt {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  'Fürstäbtissin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  'Fürstabtei {1_Capital}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  'Fürstabtei {1_Capital}'	),
	
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  'Fürstbischof {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  'Fürstbischöfin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  'Fürstbistum {1_Capital}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  'Fürstbistum {1_Capital}'	),
	
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Fürsterzbischof {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Fürsterzbischöfin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Fürsterzbistum {1_Name}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Fürsterzbistum {1_Name}'	),
	
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  'Papst {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  'Päpstin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Capital[5]} Papsttum'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Capital[5]} Papsttum'	),
	
	-- Theocracy - Protestant
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  'Pastor {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  'Pastorin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  'Gemeinde {1_Capital}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  'Gemeinde {1_Capital}'	),
	
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  'Dekan {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  'Dekanin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  'Dekanat {1_Capital}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  'Dekanat {1_Capital}'	),
	
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Regionalbischof {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Regionalbischöfin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Kirchenkreis {1_Name}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  'Kirchenkreis {1_Name}'	),
	
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  'Landesbischof {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  'Landesbischöfin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective[3]} Evangelische Kirche'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective[3]} Evangelische Kirche'	),
	
	-- Merchant Republic - Tiny
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  'Bürgermeister {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  'Bürgermeisterin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  'Freie Stadt {1_Capital}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  'Freie Stadt {1_Capital}'	),
	
	-- Merchant Republic - Land
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  'Vorderster Losunger {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  'Vorderste Losungerin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  'Freie Stadt {2_Capital}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  'Freie Stadt {2_Capital}'	),
	
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  'Oberbürgermeister {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  'Oberbürgermeisterin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  'Republik {1_Capital}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  'Republik {1_Capital}'	),
	
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  'Vorsitzender {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  'Vorsitzende {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  'Bayerischer Städtetag'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  'Bayerischer Städtetag'	),
	
	-- Merchant Republic - Sea
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  'Vorderster Losunger {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  'Vorderste Losungerin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  'Freie Stadt {2_Capital}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  'Freie Stadt {2_Capital}'	),
	
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  'Oberbürgermeister {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  'Oberbürgermeisterin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  'Republik {2_Capital}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  'Republik {2_Capital}'	),

	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  'Vorsitzender {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  'Vorsitzende {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  'Bayerischer Städtetag'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  'Bayerischer Städtetag'	),

	-- Tier 3
	
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  'Generalstaatskommissar {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  'Generalstaatskommissarin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective[3]} Ordnungszelle'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective[3]} Ordnungszelle'	),
	
	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  'Generalsekretär {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  'Generalsekretärin {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  'Bayerische Räterepublik'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  'Bayerische Räterepublik'	),

	('de_DE',	'LOC_LEADER_MALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  'Ministerpräsident {1_Name}'	),
	('de_DE',	'LOC_LEADER_FEMALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  'Ministerpräsident {1_Name}'	),
	('de_DE',	'LOC_SHORT_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  'Freistaat {1_Name}'	),
	('de_DE',	'LOC_LONG_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  'Freistaat {1_Name}'	);
--------------------------------------------------------------

-- China

--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES

	-- Tier 2
	
	-- Monarchy
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  '{1_Name}伯爵'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  '{1_Name}女伯爵'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}伯国'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}伯国'	),

	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  '{1_Name}亲王'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  '{1_Name}公主'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  '{2_Capital}亲王国'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_JNR_BAVARIA',  '{2_Capital}亲王国'	),

	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '{1_Name}公爵'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '{1_Name}女公爵'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '{1_Name}公国'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '{1_Name}公国'	),

	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Name}国王'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Name}女王'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Name}王国'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Name}王国'	),

	-- Theocracy - Military Order
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  '大团长{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_TTHEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  '大团长{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  '皇家{1_Adjective}圣乔治骑士团'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_MILITARY_ORDER_CIVILIZATION_JNR_BAVARIA',  '皇家{1_Adjective}圣乔治骑士团'	),

	-- Theocracy - Christian / Catholic
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  '亲王修道院长{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  '公主修道院长{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}亲王修道院'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_TINY_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}亲王修道院'	),
	
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  '亲王主教{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  '公主主教{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}亲王主教区'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_SMALL_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}亲王主教区'	),
	
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '亲王大主教{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '公主大主教{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '{1_Name}亲王大主教区'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '{1_Name}亲王大主教区'	),
	
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  '教皇{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  '女教皇{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}教廷'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_CHRISTIAN_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}教廷'	),
	
	-- Theocracy - Protestant
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  '牧师{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  '女牧师{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}会众'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_TINY_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}会众'	),
	
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  '主任牧师{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  '主任牧师{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}主任牧师区'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_SMALL_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}主任牧师区'	),
	
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '地区主教{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '地区女主教{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '{1_Name}主教区'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_MEDIUM_CIVILIZATION_JNR_BAVARIA',  '{1_Name}主教区'	),
	
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  '国家主教{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  '国家女主教{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective}福音教会'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_THEOCRACY_PROTESTANT_LARGE_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective}福音教会'	),
	
	-- Merchant Republic - Tiny
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  '市长{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  '市长{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}自由市'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}自由市'	),
	
	-- Merchant Republic - Land
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  '首席税务官{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  '首席女税务官{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  '{2_Capital}自由市'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_JNR_BAVARIA',  '{2_Capital}自由市'	),
	
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  '市长大人{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  '市长大人{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}共和国'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_JNR_BAVARIA',  '{1_Capital}共和国'	),
	
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  '主席{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  '主席{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  '巴伐利亚联盟'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_JNR_BAVARIA',  '巴伐利亚联盟'	),
	
	-- Merchant Republic - Sea
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  '首席税务官{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  '首席女税务官{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  '{2_Capital}自由市'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_JNR_BAVARIA',  '{2_Capital}自由市'	),
	
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  '市长大人{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  '市长大人{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  '{2_Capital}共和国'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_JNR_BAVARIA',  '{2_Capital}共和国'	),

	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  '主席{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  '主席{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  '巴伐利亚联盟'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_JNR_BAVARIA',  '巴伐利亚联盟'	),

	-- Tier 3
	
	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  '州总专员{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  '州总专员{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective}秩序细胞'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_FASCISM_CIVILIZATION_JNR_BAVARIA',  '{1_Adjective}秩序细胞'	),

	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  '总书记{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  '总书记{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  '巴伐利亚苏维埃共和国'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_COMMUNISM_CIVILIZATION_JNR_BAVARIA',  '巴伐利亚苏维埃共和国'	),

	('zh_Hans_CN',	'LOC_LEADER_MALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  '总理{1_Name}'	),
	('zh_Hans_CN',	'LOC_LEADER_FEMALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  '总理{1_Name}'	),
	('zh_Hans_CN',	'LOC_SHORT_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  '{1_Name}自由州'	),
	('zh_Hans_CN',	'LOC_LONG_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_JNR_BAVARIA',  '{1_Name}自由州'	);