-- Civilazation
-- border expansion 30%
DELETE FROM TraitModifiers
      WHERE ModifierId = 'MODIFIER_MER_THERESIAN_REFORM_FREE_MELEE_ATTACH';

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_CIVILIZATION_MER_CROWNLANDS', 'MODIFIER_VAN_AUSTRIA_BORDER_EXPANSION');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('MODIFIER_VAN_AUSTRIA_BORDER_EXPANSION', 'MODIFIER_ALL_CITIES_CULTURE_BORDER_EXPANSION', 0, 0, 0, NULL, NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('MODIFIER_VAN_AUSTRIA_BORDER_EXPANSION', 'Amount', '30');

-- +1 dilpo slot with zzzx
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_CIVILIZATION_MER_CROWNLANDS', 'MODIFIER_VAN_AUSTRIA_EXTRA_DILPO_SLOT');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('MODIFIER_VAN_AUSTRIA_EXTRA_DILPO_SLOT', 'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER', 0, 0, 0, 'BBG_UTILS_PLAYER_HAS_CIVIC_POLITICAL_PHILOSOPHY_REQSET', NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('MODIFIER_VAN_AUSTRIA_EXTRA_DILPO_SLOT', 'GovernmentSlotType', 'SLOT_DIPLOMATIC');

-- remove start bias
DELETE FROM StartBiasTerrains
      WHERE CivilizationType = 'CIVILIZATION_MER_AUSTRIA';

DELETE FROM StartBiasRivers
      WHERE CivilizationType = 'CIVILIZATION_MER_AUSTRIA';

-- uu CS to 63/67, sight to 4
UPDATE Units SET Combat = 63, RangedCombat = 67, BaseSightRange = 4 WHERE UnitType = 'UNIT_MER_GRENZER';

-- uu CS bonus range to 2
UPDATE RequirementArguments SET Value = 2 WHERE RequirementId = 'GRENZER_TERRITORY_NEARBY_REQUIREMENT' AND Name = 'MaxRange';

-- ub no great work slot
DELETE FROM Building_GreatWorks
      WHERE BuildingType = 'BUILDING_MER_COFFEE_HOUSE';

-- ub let marsh and rainforest +1 sci
INSERT INTO BuildingModifiers
SELECT 'BUILDING_MER_COFFEE_HOUSE', ModifierId
FROM BuildingModifiers
WHERE BuildingType = 'BUILDING_ZOO';

-- Leader
-- remove all
DELETE FROM TraitModifiers
      WHERE ModifierId IN ('MODIFIER_MER_CROWNLANDS_GOVERNOR_FAVOR_ATTACH', 'MODIFIER_MER_CROWNLANDS_GOVERNOR_ATTACH', 'MODIFIER_MER_CROWNLANDS_GOVERNOR_PRODUCTION_ATTACH', 'MODIFIER_MER_CROWNLANDS_DIPLOMACY_SLOT', 'MODIFIER_MER_THERESIAN_REFORMS_DISTRICT_AERODROME_HOUSING', 'MODIFIER_MER_THERESIAN_REFORMS_DISTRICT_CAMPUS_HOUSING', 'MODIFIER_MER_THERESIAN_REFORMS_DISTRICT_COMMERCIAL_HUB_HOUSING', 'MODIFIER_MER_THERESIAN_REFORMS_DISTRICT_ENCAMPMENT_HOUSING', 'MODIFIER_MER_THERESIAN_REFORMS_DISTRICT_ENTERTAINMENT_COMPLEX_HOUSING', 'MODIFIER_MER_THERESIAN_REFORMS_DISTRICT_HARBOR_HOUSING', 'MODIFIER_MER_THERESIAN_REFORMS_DISTRICT_HOLY_SITE_HOUSING', 'MODIFIER_MER_THERESIAN_REFORMS_DISTRICT_INDUSTRIAL_ZONE_HOUSING', 'MODIFIER_MER_THERESIAN_REFORMS_DISTRICT_SPACEPORT_HOUSING', 'MODIFIER_MER_THERESIAN_REFORMS_DISTRICT_THEATER_HOUSING', 'MODIFIER_MER_THERESIAN_REFORMS_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_HOUSING');


-- governored city +40% prod for districts
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_MER_THERESIAN_REFORM', 'MODIFIER_VAN_GOVERNOR_PROD_DISTRICT');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('MODIFIER_VAN_GOVERNOR_PROD_DISTRICT', 'MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION', 0, 0, 0, NULL, 'CITY_HAS_GOVERNOR_REQUIREMENTS');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('MODIFIER_VAN_GOVERNOR_PROD_DISTRICT', 'Amount', '40');

-- +1 housing for special districts
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_MER_THERESIAN_REFORM', 'VAN_THERESA_DISTRICT_HOUSING');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('VAN_THERESA_DISTRICT_HOUSING', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING', 0, 0, 0, NULL, 'BBG_IS_SPECIALTY_DISTRICT');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('VAN_THERESA_DISTRICT_HOUSING', 'Amount', 1);