-- RECIV_Bavaria_Names
-- Author: JNR
--------------------------------------------------------------

-- CityNames
--------------------------------------------------------------
INSERT OR IGNORE INTO CityNames
		(CivilizationType,				CityName)
VALUES	('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_MUNICH_CAPITAL'),	--Shared with Germany
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_NUREMBERG'),			--Shared with Germany
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_AUGSBURG'),			--Shared with Germany
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_REGENSBURG'),		--Shared with Germany
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_INGOLSTADT'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_WURZBURG'),			--Shared with Germany
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_BAYREUTH'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_PASSAU'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_COBURG'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_LANDSHUT'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_ERLANGEN'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_BAMBERG'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_SCHWEINFURT'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_FURTH'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_FREISING'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_HOF'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_AMBERG'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_ANSBACH'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_ROSENHEIM'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_KEMPTEN'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_STRAUBING'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_BAD_KISSINGEN'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_ASCHAFFENBURG'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_MEMMINGEN'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_ERDING'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_PARTENKIRCHEN'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_TRAUNSTEIN'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_NORDLINGEN'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_STARNBERG'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_OBERSTORF'),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITY_NAME_BAD_TOLZ');
--------------------------------------------------------------

-- CivilizationCitizenNames
--------------------------------------------------------------
INSERT OR IGNORE INTO CivilizationCitizenNames
		(CivilizationType,				CitizenName,								Female,	Modern)
VALUES	('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MALE_1',			0,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MALE_2',			0,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MALE_3',			0,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MALE_4',			0,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MALE_5',			0,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MALE_6',			0,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MALE_7',			0,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MALE_8',			0,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MALE_9',			0,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MALE_10',			0,		0),
		
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_1',			1,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_2',			1,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_3',			1,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_4',			1,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_5',			1,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_6',			1,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_7',			1,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_8',			1,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_9',			1,		0),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_FEMALE_10',		1,		0),

		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_1',	0,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_2',	0,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_3',	0,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_4',	0,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_5',	0,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_6',	0,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_7',	0,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_8',	0,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_9',	0,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_MALE_10',	0,		1),
		
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_1',	1,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_2',	1,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_3',	1,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_4',	1,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_5',	1,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_6',	1,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_7',	1,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_8',	1,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_9',	1,		1),
		('CIVILIZATION_JNR_BAVARIA',	'LOC_CITIZEN_JNR_BAVARIA_MODERN_FEMALE_10',	1,		1);
--------------------------------------------------------------